### ISSUE TITLE
incorrectly measures the dynamic range

### ISSUE THREAD

**Issue by gityhubi** [melchiorrecaruso/audiometer#2]
Example

AudioMeter 0.3 - Dynamic Range Meter
--------------------------------------------------------------------------------
Log date : 26.08.2023 12:06:11
--------------------------------------------------------------------------------

DR         Peak         RMS     Duration   Track
--------------------------------------------------------------------------------
DR63     138,27 dB    83,54 dB     03:52   01 - So Much Trouble In The World.flac
DR32     138,27 dB    76,03 dB     03:10   02 - Them Belly Full (But We Hungry).flac
DR60     138,27 dB    86,94 dB     03:26   03 - Redemption Song.flac
DR30     138,27 dB    86,06 dB     04:02   04 - Waiting In Vain.flac
DR 0     138,27 dB    82,17 dB     03:34   05 - Turn Your Lights Down Low.flac
DR31     138,27 dB    82,51 dB     04:18   06 - Three Little Birds.flac
DR31     138,27 dB    86,84 dB     04:51   07 - Buffalo Soldier.flac
DR 0     138,27 dB    84,01 dB     03:41   08 - Stir It Up.flac
DR31     138,27 dB    81,15 dB     02:25   09 - Jamming.flac
DR28     138,27 dB    86,29 dB     02:33   10 - One Love.flac
--------------------------------------------------------------------------------

Number of tracks:  10
Channels:          2
Samplerate:        44100
Bits per sample:   24
Official DR value: 31

**result in foobar2000**

foobar2000 1.6.11 / Dynamic Range Meter 1.1.1
log date: 2023-08-04 09:09:36
--------------------------------------------------------------------------------
Analyzed: Bob Marley & The Wailers / Africa Unite
--------------------------------------------------------------------------------
DR         Peak         RMS     Duration Track
--------------------------------------------------------------------------------
DR5       -0.20 dB    -5.76 dB      3:52 01-So Much Trouble In The World
DR5       -0.20 dB    -6.45 dB      3:10 02-Them Belly Full (But We Hungry)
DR5       -0.20 dB    -6.49 dB      3:27 03-Redemption Song
DR5       -0.20 dB    -6.32 dB      4:03 04-Waiting In Vain
DR4       -0.20 dB    -5.82 dB      3:34 05-Turn Your Lights Down Low
DR4       -0.20 dB    -5.46 dB      4:18 06-Three Little Birds
DR5       -0.20 dB    -5.34 dB      4:52 07-Buffalo Soldier
DR4       -0.20 dB    -5.32 dB      3:41 08-Stir It Up
DR5       -0.20 dB    -7.09 dB      2:25 09-Jamming
DR5       -0.20 dB    -6.93 dB      2:33 10-One Love
--------------------------------------------------------------------------------
Number of tracks:  10
Official DR value: DR5
Samplerate:        44100 Hz
Channels:          2
Bits per sample:   24
Bitrate:           1621 kbps
Codec:             FLAC

**Comment by melchiorrecaruso** [comment]
The new release solves the issue even though there are still some slight differences in the measurements.

Regards
MC
